NAME: free5gc-smf
LAST DEPLOYED: Tue Apr  2 15:48:13 2024
NAMESPACE: default
STATUS: pending-install
REVISION: 1
HOOKS:
---
# Source: free5gc-smf/templates/tests/test-connection.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
apiVersion: v1
kind: Pod
metadata:
  name: "free5gc-smf-test-connection"
  labels:
    helm.sh/chart: free5gc-smf-0.2.7
    app.kubernetes.io/name: free5gc-smf
    app.kubernetes.io/instance: free5gc-smf
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: [':80']
  restartPolicy: Never
MANIFEST:
---
# Source: free5gc-smf/templates/smf-configmap.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI, Ian Chen
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: free5gc-smf-configmap
  labels:
    app: free5gc
data:
  smfcfg.yaml: |
    info:
      version: 1.0.7
      description: SMF initial local configuration

    configuration:
      serviceNameList:
        - nsmf-pdusession
        - nsmf-event-exposure
        - nsmf-oam

      sbi:
        scheme: http
        registerIPv4: free5gc-smf-service # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: 80
        tls:
          key: ../cert/smf.key
          pem: ../cert/smf.pem

      nrfUri: http://nrf-nnrf:8000

      pfcp:
        nodeID: 10.100.50.244
        listenAddr: 10.100.50.244
        externalAddr: 10.100.50.244
      smfName: SMF
      snssaiInfos:
        - sNssai:
            sst: 1
            sd: 010203
          dnnInfos: # DNN information list
            - dnn: internet # Data Network Name
              dns: # the IP address of DNS
                ipv4: 8.8.8.8
                ipv6: 2001:4860:4860::8888
        - sNssai:
            sst: 1
            sd: 112233
          dnnInfos: # DNN information list
            - dnn: internet # Data Network Name
              dns: # the IP address of DNS
                ipv4: 8.8.8.8
                ipv6: 2001:4860:4860::8888
        - sNssai:
            sst: 2
            sd: 112234
          dnnInfos:
            - dnn: internet
              dns:
                ipv4: 8.8.8.8
                ipv6: 2001:4860:4860::8888
      plmnList: # the list of PLMN IDs that this SMF belongs to (optional, remove this key when unnecessary)
        - mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
          mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
      userplaneInformation: # list of userplane information
        upNodes: # information of userplane node (AN or UPF)
          gNB1: # the name of the node
            type: AN # the type of the node (AN or UPF)
          UPF:  # the name of the node
            type: UPF # the type of the node (AN or UPF)
            nodeID: 10.100.50.241 # the IP/FQDN of N4 interface on this UPF (PFCP)
            addr: 10.100.50.241 # the IP/FQDN of N4 interface on this UPF (PFCP)
            sNssaiUpfInfos: # S-NSSAI information list for this UPF
                  - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
                      sst: 1 # Slice/Service Type (uinteger, range: 0~255)
                      sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
                    dnnUpfInfoList: # DNN information list for this S-NSSAI
                      - dnn: internet
                        pools:
                          - cidr: 10.1.0.0/17
                        staticPools:
                          - cidr: 10.1.64.0/24
                  - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
                      sst: 1 # Slice/Service Type (uinteger, range: 0~255)
                      sd: 112233 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
                    dnnUpfInfoList: # DNN information list for this S-NSSAI
                      - dnn: internet
                        pools:
                          - cidr: 10.1.128.0/17
                        staticPools:
                          - cidr: 10.1.192.0/24
            interfaces: # Interface list for this UPF
                  - interfaceType: N3 # the type of the interface (N3 or N9)
                    endpoints: # the IP address of this N3/N9 interface on this UPF
                      - 10.100.50.233
                    networkInstances:
                      - internet # Data Network Name (DNN)
        links: # the topology graph of userplane, A and B represent the two nodes of each link
          - A: gNB1
            B: UPF
      locality: area1 # Name of the location where a set of AMF, SMF and UPFs are located
      
      t3591:
        enable: true     # true or false
        expireTime: 16s   # default is 6 seconds
        maxRetryTimes: 3 # the max number of retransmission
      # retransmission timer for pdu session release command
      t3592:
        enable: true     # true or false
        expireTime: 16s   # default is 6 seconds
        maxRetryTimes: 3 # the max number of retransmission

    logger:
      enable: true
      level: info
      reportCaller: false


  uerouting.yaml: |
    info:
      version: 1.0.7
      description: Routing information for UE
    ueRoutingInfo:
      UE1: # Group Name
        members:
        - imsi-208930000000003 # Subscription Permanent Identifier of the UE
        topology: # Network topology for this group (Uplink: A->B, Downlink: B->A)
        # default path derived from this topology
        # node name should be consistent with smfcfg.yaml
          - A: gNB1
            B: BranchingUPF
          - A: BranchingUPF
            B: AnchorUPF1
        specificPath:
          - dest: 10.100.100.26/32 # the destination IP address on Data Network (DN)
            # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
            # The UPF's name should be consistent with smfcfg.yaml
            path: [BranchingUPF, AnchorUPF2]
      
      UE2: # Group Name
        members:
        - imsi-208930000000004 # Subscription Permanent Identifier of the UE
        topology: # Network topology for this group (Uplink: A->B, Downlink: B->A)
        # default path derived from this topology
        # node name should be consistent with smfcfg.yaml
          - A: gNB1
            B: BranchingUPF
          - A: BranchingUPF
            B: AnchorUPF1
        specificPath:
          - dest: 10.100.100.16/32 # the destination IP address on Data Network (DN)
            # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
            # The UPF's name should be consistent with smfcfg.yaml
            path: [BranchingUPF, AnchorUPF2]
---
# Source: free5gc-smf/templates/smf-service.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
apiVersion: v1
kind: Service
metadata:
  name: free5gc-smf-service
  labels:
    helm.sh/chart: free5gc-smf-0.2.7
    app.kubernetes.io/name: free5gc-smf
    app.kubernetes.io/instance: free5gc-smf
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    project: free5gc
    nf: smf
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: free5gc-smf
    app.kubernetes.io/instance: free5gc-smf
    project: free5gc
    nf: smf
---
# Source: free5gc-smf/templates/smf-deployment.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-smf-smf
  labels:
    helm.sh/chart: free5gc-smf-0.2.7
    app.kubernetes.io/name: free5gc-smf
    app.kubernetes.io/instance: free5gc-smf
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    project: free5gc
    nf: smf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: free5gc-smf
      app.kubernetes.io/instance: free5gc-smf
      project: free5gc
      nf: smf
  template:
    metadata:
      annotations:
        
        k8s.v1.cni.cncf.io/networks: '[
            { "name": "n4network-free5gc-smf",
              "interface": "n4",
              "ips": [ "10.100.50.244/29" ],
              "gateway": [ "10.100.50.246" ]
            }]'
        checksum/config: 9cbcf525e252c70d8975dc62e2fa8813aacbdd9e37c4443265d242ff38d1e1fd
      labels:
        app.kubernetes.io/name: free5gc-smf
        app.kubernetes.io/instance: free5gc-smf
        project: free5gc
        nf: smf
    spec:
      imagePullSecrets:
        []
      securityContext:
        {}
      initContainers:
      - name: wait-nrf
        image: towards5gs/initcurl:1.0.0
        env:
        - name: DEPENDENCIES
          value: http://nrf-nnrf:8000
        command: ['sh', '-c', 'set -x; for dependency in $DEPENDENCIES; do while [ $(curl --insecure --connect-timeout 1 -s -o /dev/null -w "%{http_code}" $dependency) -ne 200 ]; do echo waiting for dependencies; sleep 1; done; done;']

      containers:
      - name: smf
        image: towards5gs/free5gc-smf:latest
        imagePullPolicy: Always
        securityContext:
            {}
        ports:
        - name: nsmf
          containerPort: 80
        - name: n4
          containerPort: 8805
          protocol: UDP
        command: ["./smf"]
        args: ["-c", "../config/smfcfg.yaml", "-u", "../config/uerouting.yaml"]
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /free5gc/config/
          name: free5gc-smf-volume
        resources:
            requests:
              cpu: 100m
              memory: 128Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []

      volumes:
      - name: free5gc-smf-volume
        projected:
          sources:
          - configMap:
              name: free5gc-smf-configmap
              items:
              - key: smfcfg.yaml
                path: smfcfg.yaml
              - key: uerouting.yaml
                path: uerouting.yaml
---
# Source: free5gc-smf/templates/smf-hpa.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
---
# Source: free5gc-smf/templates/smf-ingress.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
---
# Source: free5gc-smf/templates/smf-n4-nad.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: n4network-free5gc-smf
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "ipvlan",
          "capabilities": { "ips": true },
          "master": "eth0",
          "mode": "l2",
          "ipam": {
            "type": "static",
            "routes": [
              {
                "dst": "0.0.0.0/0",
                "gw": "10.100.50.246"
              }
            ]
          }
        }
      ]
    }'

NOTES:
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=free5gc-smf,app.kubernetes.io/instance=free5gc-smf" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT
