NAME: free5gc-udm
LAST DEPLOYED: Mon Apr  8 14:55:17 2024
NAMESPACE: default
STATUS: pending-install
REVISION: 1
HOOKS:
---
# Source: free5gc-udm/templates/tests/test-connection.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
apiVersion: v1
kind: Pod
metadata:
  name: "free5gc-udm-test-connection"
  labels:
    helm.sh/chart: free5gc-udm-0.2.7
    app.kubernetes.io/name: free5gc-udm
    app.kubernetes.io/instance: free5gc-udm
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: [':80']
  restartPolicy: Never
MANIFEST:
---
# Source: free5gc-udm/templates/udm-configmap.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI, Ian Chen
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: free5gc-udm-configmap
  labels:
    app: free5gc
data:
  udmcfg.yaml: |
    info:
      version: 1.0.3
      description: UDM initial local configuration

    configuration:
      serviceNameList:
        - nudm-sdm
        - nudm-uecm
        - nudm-ueau
        - nudm-ee
        - nudm-pp

      sbi:
        scheme: http
        registerIPv4: free5gc-udm-service # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: 80
        tls:
          key: ../cert/udm.key
          pem: ../cert/udm.pem

      nrfUri: http://nrf-nnrf:8000
      nrfCertPem: ../cert/nrf.pem # NRF Certificate
      # test data set from TS33501-f60 Annex C.4
      SuciProfile:
        - ProtectionScheme: 1 # Protect Scheme: Profile A
          PrivateKey: c53c22208b61860b06c62e5406a7b330c2b577aa5558981510d128247d38bd1d
          PublicKey: 5a8d38864820197c3394b92613b20b91633cbd897119273bf8e4a6f4eec0a650
        - ProtectionScheme: 2 # Protect Scheme: Profile B
          PrivateKey: F1AB1074477EBCC7F554EA1C5FC368B1616730155E0041AC447D6301975FECDA
          PublicKey: 0472DA71976234CE833A6907425867B82E074D44EF907DFB4B3E21C1C2256EBCD15A7DED52FCBB097A4ED250E036C7B9C8C7004C4EEDC4F068CD7BF8D3F900E3B4

    logger:
      enable: true
      level: info
      reportCaller: false
---
# Source: free5gc-udm/templates/udm-service.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
apiVersion: v1
kind: Service
metadata:
  name: free5gc-udm-service
  labels:
    helm.sh/chart: free5gc-udm-0.2.7
    app.kubernetes.io/name: free5gc-udm
    app.kubernetes.io/instance: free5gc-udm
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    project: free5gc
    nf: udm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: free5gc-udm
    app.kubernetes.io/instance: free5gc-udm
    project: free5gc
    nf: udm
---
# Source: free5gc-udm/templates/udm-deployment.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-udm-udm
  labels:
    helm.sh/chart: free5gc-udm-0.2.7
    app.kubernetes.io/name: free5gc-udm
    app.kubernetes.io/instance: free5gc-udm
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    project: free5gc
    nf: udm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: free5gc-udm
      app.kubernetes.io/instance: free5gc-udm
      project: free5gc
      nf: udm
  template:
    metadata:
      annotations:
        
        checksum/config: c9561328e5981ad0406960f9dd7a011eb0a3c068d37931aa2b668a81aed35ccb
      labels:
        app.kubernetes.io/name: free5gc-udm
        app.kubernetes.io/instance: free5gc-udm
        project: free5gc
        nf: udm
    spec:
      imagePullSecrets:
        []
      securityContext:
        {}
      initContainers:
      - name: wait-nrf
        image: towards5gs/initcurl:1.0.0
        env:
        - name: DEPENDENCIES
          value: http://nrf-nnrf:8000
        command: ['sh', '-c', 'set -x; for dependency in $DEPENDENCIES; do while [ $(curl --insecure --connect-timeout 1 -s -o /dev/null -w "%{http_code}" $dependency) -ne 200 ]; do echo waiting for dependencies; sleep 1; done; done;']

      containers:
      - name: udm
        image: towards5gs/free5gc-udm:latest
        imagePullPolicy: Always
        securityContext:
            {}
        ports:
        - containerPort: 80
        command: ["./udm"]
        args: ["-c", "../config/udmcfg.yaml"]
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /free5gc/config/
          name: free5gc-udm-volume
        resources:
            requests:
              cpu: 100m
              memory: 128Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []

      volumes:
      - name: free5gc-udm-volume
        projected:
          sources:
          - configMap:
              name: free5gc-udm-configmap
---
# Source: free5gc-udm/templates/udm-hpa.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
---
# Source: free5gc-udm/templates/udm-ingress.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#

NOTES:
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=free5gc-udm,app.kubernetes.io/instance=free5gc-udm" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT
