NAME: free5gc-udr
LAST DEPLOYED: Tue Apr  2 15:48:13 2024
NAMESPACE: default
STATUS: pending-install
REVISION: 1
HOOKS:
---
# Source: free5gc-udr/templates/tests/test-connection.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
apiVersion: v1
kind: Pod
metadata:
  name: "free5gc-udr-test-connection"
  labels:
    helm.sh/chart: free5gc-udr-0.2.7
    app.kubernetes.io/name: free5gc-udr
    app.kubernetes.io/instance: free5gc-udr
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: [':80']
  restartPolicy: Never
MANIFEST:
---
# Source: free5gc-udr/templates/udr-configmap.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI, Ian Chen
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: free5gc-udr-configmap
  labels:
    app: free5gc
data:
  udrcfg.yaml: |
    info:
      version: 1.0.2
      description: UDR initial local configuration

    configuration:
      sbi:
        scheme: http
        registerIPv4: free5gc-udr-service # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: 80
        tls:
          key: ../cert/udr.key
          pem: ../cert/udr.pem

      mongodb:
        name: free5gc
        url: mongodb://mongodb:27017

      nrfUri: http://nrf-nnrf:8000

    logger:
      enable: true
      level: info
      reportCaller: false
---
# Source: free5gc-udr/templates/udr-service.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
apiVersion: v1
kind: Service
metadata:
  name: free5gc-udr-service
  labels:
    helm.sh/chart: free5gc-udr-0.2.7
    app.kubernetes.io/name: free5gc-udr
    app.kubernetes.io/instance: free5gc-udr
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    project: free5gc
    nf: udr
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: free5gc-udr
    app.kubernetes.io/instance: free5gc-udr
    project: free5gc
    nf: udr
---
# Source: free5gc-udr/templates/udr-deployment.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-udr-udr
  labels:
    helm.sh/chart: free5gc-udr-0.2.7
    app.kubernetes.io/name: free5gc-udr
    app.kubernetes.io/instance: free5gc-udr
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    project: free5gc
    nf: udr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: free5gc-udr
      app.kubernetes.io/instance: free5gc-udr
      project: free5gc
      nf: udr
  template:
    metadata:
      annotations:
        
        checksum/config: 17d524d93501e1b429ce2058caeecbb3d5c8d8baa202b25c8015de6e530cbfc1
      labels:
        app.kubernetes.io/name: free5gc-udr
        app.kubernetes.io/instance: free5gc-udr
        project: free5gc
        nf: udr
    spec:
      imagePullSecrets:
        []
      securityContext:
        {}
      initContainers:
      - name: wait-nrf
        image: towards5gs/initcurl:1.0.0
        env:
        - name: DEPENDENCIES
          value: http://nrf-nnrf:8000
        command: ['sh', '-c', 'set -x; for dependency in $DEPENDENCIES; do while [ $(curl --insecure --connect-timeout 1 -s -o /dev/null -w "%{http_code}" $dependency) -ne 200 ]; do echo waiting for dependencies; sleep 1; done; done;']

      containers:
      - name: udr
        image: towards5gs/free5gc-udr:latest
        imagePullPolicy: Always
        securityContext:
            {}
        ports:
        - containerPort: 80
        command: ["./udr"]
        args: ["-c", "../config/udrcfg.yaml"]
        env:
          - name: DB_URI
            value: mongodb://mongodb/free5gc
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /free5gc/config/
          name: free5gc-udr-volume
        resources:
            requests:
              cpu: 100m
              memory: 128Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []

      volumes:
      - name: free5gc-udr-volume
        projected:
          sources:
          - configMap:
              name: free5gc-udr-configmap
---
# Source: free5gc-udr/templates/udr-hpa.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
---
# Source: free5gc-udr/templates/udr-ingress.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#

NOTES:
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=free5gc-udr,app.kubernetes.io/instance=free5gc-udr" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT
