#
# Software Name : free5gc-compose
#
apiVersion: v1
kind: Service
metadata:
  name: {{ include "free5gc-chf.fullname" . }}
  labels:
    {{- include "free5gc-chf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "free5gc-chf.selectorLabels" . | nindent 4 }}
